version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/project/
    command: >
      sh -c "gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend